name: Qodana

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: ğŸ§­ Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0

      - name: ğŸ Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: ğŸ§¾ Run tests with coverage
        env:
          ENV: test
        run: |
          pip install --upgrade pip build
          pip install .
          coverage run -m pytest
          coverage xml -o .qodana/code-coverage/coverage.xml

      - name: ï¸ğŸ“‚ Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: py-coverage-data
          path: .qodana/code-coverage

      - name: 'ğŸ” Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: |
            --linter,qodana-python-community,
            --within-docker,false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_174571135 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'