name: SonarQube

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: ğŸ§­ Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ğŸ Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: ğŸ§¾ Run tests with coverage
        env:
          ENV: test
        run: |
          pip install --upgrade pip build
          pip install .
          coverage run -m pytest
          coverage xml -o .coverage-reports/coverage-backend.xml

      - name: ï¸ğŸ“‚ Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: py-coverage-data
          path: .coverage-reports/coverage.xml

      - name: 'ğŸ” SonarQube Scan'
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          ENV: test